### ISSUE TITLE
Colors don't look quite right?

### ISSUE THREAD

**Issue by altano** [iamskok/gatsby-prismjs-dracula#1]
Have I configured things wrong or is does this theme not perfectly match Dracula?

This theme:
![image](https://user-images.githubusercontent.com/1009/73060799-800d9880-3e4d-11ea-8352-6613e449e4ac.png)

Dracula in VS Code:
![image](https://user-images.githubusercontent.com/1009/73060824-8ef44b00-3e4d-11ea-91f5-a4869a235f07.png)

**Comment by iamskok** [comment]
@altano it doesn’t perfectly match Dracula. Let me know if you want to submit a PR.

**Comment by altano** [comment]
This Dracula theme for Prism.js is almost perfect in case anyone feels like adopting it to this plugin (for easier installation): https://github.com/dracula/prism/blob/master/css/dracula-prism.css
